name: AWS CD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/checkout@v2
      - name: Setup AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GithubActionsRoleBrancas
          role-session-name: github-action
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setting stage and stack name
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "STAGE=dev" >> $GITHUB_ENV
          else
            echo "Invalid branch name!" && exit 1
          fi
          echo "STACK_NAME=QuantumBrosStackFront${{env.STAGE}}" >> $GITHUB_ENV
      - name: Installing Dependencies
        run: |
          npm install
          npm install -g aws-cdk
      - name: Build and Export
        run: |
          npm run build
        env:
          VITE_STAGE: ${{ env.VITE_STAGE}}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
      - name: Setup envs
        run: |
          echo "Stage: ${{ env.STAGE }}"
          echo AWS_REGION=${{ vars.AWS_REGION }} >> $GITHUB_ENV
          echo AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
          echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
          echo GITHUB_REF_NAME=${{ env.STAGE }} >> $GITHUB_ENV
          echo ACM_CERTIFICATE_ARN=${{ secrets.ACM_CERTIFICATE_ARN }} >> $GITHUB_ENV
      - name: Deploy with CDK
        run: |
          cd iac
          npm install
          cdk synth
          cdk deploy --require-approval never
      - name: Set CloudFront ID
        run: |
          CLOUD_FRONT_ID=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='QuantumBrosFrontDistributionId${{env.STAGE}}'].OutputValue" --output text)
          echo "CLOUD_FRONT_ID='$CLOUD_FRONT_ID'" >> $GITHUB_ENV
      - name: Set AWS Bucket
        run: |
          echo "Setting AWS Bucket"
          AWS_BUCKET=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='QuantumBrosFrontDistributionId${{env.STAGE}}'].OutputValue" --output text)
          echo "AWS_BUCKET='$AWS_BUCKET'" >> $GITHUB_ENV
      - name: Check if bucket exists
        run: |
          if [ -z "${{env.AWS_BUCKET}}" ]; then
            echo "Bucket name is empty!"
            exit 1
          fi
          aws s3 ls s3://${{env.AWS_BUCKET}} || (echo "Bucket does not exist or is inaccessible" && exit 1)
      - name: Upload to S3
        run: |
          aws s3 cp dist s3://${{env.AWS_BUCKET}}/ --recursive --region ${{ env.AWS_REGION }}
      - name: Clear CDN cache
        run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*" --region us-east-1
